import * as vscode from 'vscode';

export class ProofCodeCodeActionProvider implements vscode.CodeActionProvider {
  public static readonly providedCodeActionKinds = [vscode.CodeActionKind.QuickFix];

  public provideCodeActions(
    document: vscode.TextDocument,
    _range: vscode.Range | vscode.Selection,
    context: vscode.CodeActionContext,
    _token: vscode.CancellationToken
  ): vscode.CodeAction[] {
    const actions: vscode.CodeAction[] = [];

    // Filter diagnostics generated by ProofCode
    const proofCodeDiagnostics = context.diagnostics.filter(
      (diag) => diag.source === 'ProofCode'
    );

    for (const diag of proofCodeDiagnostics) {
      const lineIdx = diag.range.start.line;
      const line = document.lineAt(lineIdx);
      const lineText = line.text;
      const indentMatch = lineText.match(/^\s*/);
      const indent = indentMatch ? indentMatch[0] : '';

      // 1. Quick Fix for PC-REL-006: Unhandled Async Operation
      if (diag.code === 'PC-REL-006') {
        const action = new vscode.CodeAction(
          '🛡️ ProofCode: Wrap in try/catch block',
          vscode.CodeActionKind.QuickFix
        );
        action.isPreferred = true;
        action.diagnostics = [diag];

        const edit = new vscode.WorkspaceEdit();
        const wrapped = `${indent}try {\n${indent}  ${lineText.trim()}\n${indent}} catch (error) {\n${indent}  console.error('Async operation failed:', error);\n${indent}}`;
        edit.replace(document.uri, line.range, wrapped);
        action.edit = edit;
        actions.push(action);
